import com.google.gson.annotations.SerializedName

 data class ShapeModel (
		@SerializedName("id") val id : String?= "",
		@SerializedName("title") val title : String?= "",
		@SerializedName("description") val description : String?= "",
		@SerializedName("datetime") val datetime : Int?= 0,
		@SerializedName("cover") val cover : String?= "",
		@SerializedName("cover_width") val cover_width : Int?= 0,
		@SerializedName("cover_height") val cover_height : Int?= 0,
		@SerializedName("account_url") val account_url : String?= "",
		@SerializedName("account_id") val account_id : Int?= 0,
		@SerializedName("privacy") val privacy : String?= "",
		@SerializedName("layout") val layout : String?= "",
		@SerializedName("views") val views : Int?= 0,
		@SerializedName("link") val link : String?= "",
		@SerializedName("ups") val ups : Int?= 0,
		@SerializedName("downs") val downs : Int?= 0,
		@SerializedName("points") val points : Int?= 0,
		@SerializedName("score") val score : Int?= 0,
		@SerializedName("is_album") val is_album : Boolean = false,
		@SerializedName("vote") val vote : String?= "",
		@SerializedName("favorite") val favorite : Boolean = false,
		@SerializedName("nsfw") val nsfw : Boolean = false,
		@SerializedName("section") val section : String?= "",
		@SerializedName("comment_count") val comment_count : Int?= 0,
		@SerializedName("favorite_count") val favorite_count : Int?= 0,
		@SerializedName("topic") val topic : String?= "",
		@SerializedName("topic_id") val topic_id : Int?= 0,
		@SerializedName("images_count") val images_count : Int?= 0,
		@SerializedName("in_gallery") val in_gallery : Boolean = false,
		@SerializedName("is_ad") val is_ad : Boolean = false,
		@SerializedName("tags") val tags : List<String?>  = ArrayList(),
		@SerializedName("ad_type") val ad_type : Int?= 0,
		@SerializedName("ad_url") val ad_url : String?= "",
		@SerializedName("in_most_viral") val in_most_viral : Boolean = false,
		@SerializedName("include_album_ads") val include_album_ads : Boolean = false,
		@SerializedName("images") val images : List<ImagesModel>  = ArrayList<ImagesModel>(),
		@SerializedName("ad_config") val ad_config : AdConfig?
)